### ISSUE TITLE
Initial redirect appears wrong. 

### ISSUE THREAD

**Issue by develroo** [Aperture-Development/friendup-docker#8]
So using the default `.env` or even editing the `DOCKER_FRIEND_DOMAIN` variable, accessing the container on port 6502 will always cause a redirect to 

`http://localhost/webclient/index.html` 

this of course is wrong because no port is included. The redirect should be to 

`http://$domain:6502/webclient/index.html`

It is curious also that he above variable  is not being passed through either.

**Comment by ApertureDevelopment** [comment]
You need to include the port with the environment variable when you plan connecting to the port directly. Otherwise you use a apache reverse proxy or a nginx reverse proxy to access FriendUP.

**Comment by ApertureDevelopment** [comment]
Closed due to no reply within 3 days
